apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - nginx-deployment.yaml
  - nginx-service.yaml
configMapGenerator:
  - name: nginx-index-html
    files:
      - index.html
namespace: nginx
